[package]
name = "blockless-sdk"
version = "0.1.0"
authors = ["Join.G"]
description = "blockless sdk"
keywords = ["blockless", "sdk"]
readme = "README.md"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
json = "0.12"