[package]
name = "blockless-sdk"
version = "0.1.2"
authors = ["Join.G"]
description = "blockless runtime sdk"
keywords = ["blockless", "sdk"]
readme = "README.md"
edition = "2021"
license = "MIT/Apache-2.0"
repository = "https://github.com/blocklessnetwork/sdk-rust"

[[bin]]
name = "exam1"

[dependencies]
json = "0.12"